-- Insert stops data
INSERT INTO stops (name) VALUES
('Peace Avenue'),
('DLC Bldg. (McArthur Hi-way, Balscogan)'),
('San Antonio VII (front GSIS)'),
('Davao Exec. Homes (Quimpo Blvd.)'),
('SM City Davao'),
('Philhealth Office'),
('Agro School Foundation'),
('Almendras Gym'),
('BPI (Claveria)'),
('Guerrero cor. Magsaysay Ave.'),
('F. Bangoy cor. Magsaysay Ave.'),
('Magsaysay Ave. (Park)'),
('Bago Aplaya'),
('DXSS (Bangkal)'),
('Tahimik Avenue'),
('Matina Crossing'),
('ABS-CBN Junction'),
('Ecoland Terminal Crossing'),
('Roxas Avenue'),
('Abapo Residence'),
('Movie Homes'),
('Jardin Residence'),
('San Andres Chapel'),
('Magno Farm'),
('Dacudao Village'),
('Pola Residence'),
('El Dorado Farm'),
('Country Homes'),
('Kingdom Hall (Jehovah)'),
('Buhangin Memorial Park'),
('Milan'),
('Watusi St.'),
('DLPC Bajada'),
('Victoria Plaza'),
('Gaisano Mall'),
('Regina Complex'),
('Corner San Pedro & Iñigo (Anda) Sts.'),
('Bankerohan'),
('Catigan Brgy. Hall'),
('EVN Farm'),
('U-One Trading (Buhangin)'),
('NHA Crossing (San Antonio Buhangin)'),
('Communal'),
('Dacoville'),
('Darong'),
('Baracatan'),
('Toril'),
('Doña Pilar Subd.'),
('Bunawan'),
('Sasa'),
('Cabantian'),
('Emily Homes'),
('Suraya Homes'); 